version: '2'
services:
  app:
      build: ./server
      depends_on:
        - mysql
        - redis
        - mongo
      links:
        - mysql
        - redis
        - mongo
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PORT=5000
        - NODE_ENV=development
      ports:
        - "5000:5000"
      restart: always
      volumes:
        - ./server:/docker
        - /docker/node_modules
  mongo:
      restart: always
      image: mongo:latest
      expose:
        - "27017"
      ports:
        - "27017"
  redis:
    image: redis:latest
    restart: always
    container_name: cache
    expose:
      - 6379
    ports:
      - 6379

  mysql:
    image: mysql:5.7.17
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workflow
      MYSQL_USER: workflow
      MYSQL_PASSWORD: workflow
    expose:
      - "3306"
    ports:
      - "3306"